// I really don't know what this is for.

#include "\Headers\includes.h"

task main() {
	Sound_Unmute();
	Sound_SetVolume(4);

	while (true) {
		Sound_Moo();
		while (Sound_IsPlaying()==true) {
			Time_Wait(1000);
		}
	}
}

//$$$$$$$$$$$$$$$$$$$$$ZOZZ$$$$$$Z$ZZ$$$$$$$$$$$$ZZZZZ$ZO$ZZZ$$$$$$ZOZOOOOZOOZZZOZZOZZ$ZZZZ$ZO$7$$$$$$ZZ$$$$$$ZZZZOZ$$$Z$$
//$$$$$$$$$$$$$Z$ZZZZZOZZOZ$$$$$$ZZZOO$$$$$$$Z$Z$$$$$$$$$$$ZZ$ZZZZO88OOOOOZZZOZ$ZZZZZZZ$$$$$$$$ZZZ$$$$$Z$$OOZZ$$$$$$$$$$$$
//ZZ$Z$ZZ7$777$$$$$7$$$$$$$$$$$ZZOOOZZ$$ZZZZZZZZZ$$$Z$Z$$$$ZZZ$$Z$$$$ZZZOZOZZ$$Z$ZZ$$ZZ$$ZZZ$$$$$OOZZZZZOZO888Z8ZOO$ZZZZZZ
//ZZZZ$$$$$$7777$ZZZZZZZOZZZZZ$$ZZOOOZZZ$$Z$$$$$$ZZZOZZZZZZ$$$Z$$ZZ$$$$$$77$$7$$$Z$$$ZZ$$$OOOZOOZ$ZZZZO888888OOOZZZZZZ$$ZZ
//$$$$$$$$77$777$ZZOZZZOZZZZZZZZ$ZOOOOZOOO$$$Z8O8O8O88ZOZZZZZZZZZZZZZZZZ$$$77$ZZ$$$$$$$Z$$7$$7$$$$$$$$$$$Z$$$ZOOZZOZ$ZZ$ZZ
//8OOOOZZ$$$$$$$$$ZZ$$$$ZZ$$$$$$$$$$$$$$$$ZZZZZOD8Z$ZZZ$$$$$$$$7$7$$$$ZZZ$$$7ZZ7$$$$$$7$$ZZ$$Z$ZZ$Z$ZZZZ$ZZOZZ$Z$7$$$$$Z$$
//ZZ$$$$$$$$$7$$$$Z$$$$$$$$$$$$$$OOZZZOZZ$$$$Z$Z7$$Z$$Z$$$$77$$$$$$$7$OOO8ZZ$Z$ZZZ$$$$$$ZOZOOZZZZ$Z$Z$ZZZZOZZOZZZZ$$7$$$$$
//$ZZZ$$Z$$Z$Z$$Z$$$$$$7$$$ZZZZO8OZZOOO8OZ$$$$$$$$Z$$$77$$$7$$$$$$$$$$$7$$$$$$$$$$ZZZOO8OOOOOOOZZZ$$$$$$ZZZ$$$$$$$ZZZZZZZZ
//7$Z$Z$$ZZZZ$$Z$7ZNNNDOZ$$$$$$$Z$$Z$ZZZZZ$ZZZ$$$$7$$Z$$ZZOZOZOOO$$$$ZO$$$$$Z$$$$$$ZZZOZZZZZZ$77$$ZZ$$ZZZZ$Z$$$Z$$$$$$Z$$$
//$$$Z$7$$$$$$7$ZZNDDNDNNM8$$7$$$$$$$$$$$$7$$$$$ZZ7$ZZZZZOZZZZZOOZZZZOOZZ8O8OOZZO$ZZ$OZ$ZZZZ8OZZ$$$$$IZZ$Z$ZZOZ$OZ$$$ZZ$Z$
//$$7Z77OMMMMD7$7DM+:.+,,~D8Z777Z$$$$$77$$7ZZO$$ZZ$$ZOO888OZO$Z$$$OOZZ8D888OZO88OOZOO$I+=:........,7NMNDN77ZZZ$Z$$$ZZZ7$Z$
//ZZZZZZNMNDMMMNMMN8..,.IDNNMOMNMMMD$?~,:::,:,I8NNNNNNMNMMMMMMMMMMMMMNNNNNNNNMNMMMN+=:::::,,.,,..:=N8DD8D8DO$ZOZZZOOZOZ$ZZ
//ZZOO$7$DMNNNMMNMNN:,,IDDNNNMMNOMMNMMMM7:,::::,.~~7?$=MNNNNMMMMMMNNNMMNNNNNNNNMNNMMO,.,,,,:,,,,,,:,NMMMNNNMOOZ$Z$ZOOZZOZZ
//7$$ZZ$$$ONMNMMMND88+8D88DNMM~=NMMMMMNNM:,:,,,,:::,,,,:DDMNMMMMMNNMMMMMMNNNNNNNNNMNM+...?MNO=,,,::7OMMNNDDDN$$ZOZ$Z$ZZZZ$
//ZZZZZZZ$Z$7$Z7NNNNNNNDDNMNMNNDNNMMMMMMN8,,,,::,,,,..,,.MDNMMMMMMMMMMMMMMNNNMMMMMNNNI,..8DDDNNNMDMMNNNDDNDNNZ7Z$ZZ$$Z$O88
//$ZOOO$$OOZOO$$MNMNNNMNNDDNMMMNNNNMMMMMNNZ,:::,,,,,,...,.MNNNMMMMMMMMMMMMMMMMMMMMMNN$...Z8DDDNNNMNNND8DNNNDN$OZ$$Z$$$ZZDD
//$7$ZZOZ$7$$Z$7DMNMMNNNNDMMMMMMNNNMMMNNNMM=:::,,,,,,.,,,8NMMMMMMMMMMMMMMMMMMMMMMMMD87...Z8O8DDNNNNNDDDNNNDNMZ$ZZZZZZZZZ$O
//OOOOZ$Z$ZZOOO8OM8MMNNDDNMMMMNDNNNNMMMNMMN$,:,,,,,,,.,.ODNNNMMMMMMMMMMNNNNNNMMMMNN8O8.,:DDD88DNNDD88NNNMDN8NZZZ$$ZZ$ZZZZZ
//8OZOO8O8OZ$ZZZOMNNMNNDNMMMNNNDNNNMMMMNMMN8.:..,,,,,,.~DNNNNNMMMMMMMNNNNNNNNNNNMND88D.,.+88D8DNNDDDNNMNNMOD8$$$Z$$ZZZZZ$Z
//8OZO88O8O$$ZZ$$DDDM8NDMMMMMNNDNNNMNMMMMNMN.:,,,,,,,,,.DDNNNNMMMNNNNNNNNNNNNNNMND888O....D8DDNNNDNNMMNNMMZDZOZZOZ$ZZO$ZZ$
//OZZZOOOZZOZZZO7NN88O8NMMMMMMNDNMMMNMMNMNNNN,,,,,,,,,..+8NNNNMNNNNNNNNNNNNNNNNNDD888:....:DD8DDDDMNMNDDNNDDZZO8OO8O88OOOO
//$$$Z$$$Z$$$$$Z7MNN88=DNMMMMNNNMMMNMMMNN8DDN~,.,.,,.,,,.MDNNNMNNNNNNNNNNNNNNNNDD8D8I........~7OZ$MMDDDNM8??O$O8Z$ZZZZZO88
//$$$$ZOOOZZZZZZ8MMNMMMN8$MMMNNNMMMMMMNDDNDNN7..=+Z7,,...~NDNDNNNNNNNDDDDNNDDDDD8888DI.,.......,,~=MNNDNM$?ZZ$ZZOOOZ7$$$ZZ
//$O$$Z$ZZZOZOZO$Z$$ODNNMMMNMNNMMMMMMNDDMNDDDZ.DO88O+.,:,.,DDNNNNNNNDNNNDDDDDDDDDD88OO,,,.....,,:~,,~?DDNZ?Z$ZZOOOZ$Z$$$$$
//$$ZZZZ$$ZZOZZ$ZZZZZZOMMMMMNNMNMMMNMDND8DD8DN8NDD8DN?,,.,:.D8NNNNNDNDNNDDDDDDDDD888DZ.,,,,,.,::,,,,:?DDN7,8ZO$ZZZ$$$ZZZZZ
//$$$$ZZOOZZZOZOZZ$$Z$$$MMMMNMMMNNDNNNNDDD8DDMMMMNDDDD,,,,,,.=DDDNDNNNDDD8DDDDD88D88DD,,,:~~~~:~,,,,,DDNO?,OZ$$$$$$77$77$Z
//$$$OZ$$Z7$$Z$$$Z$ZZZZZZMMMMMMMNNNNNNDDNNDDNNMMNMDDDDD.:.,,,IDDNNDDDD8DDDDDDDDDD8DDNN,,::==~~:,,,..:DDN7+.7Z$$$$Z$$Z$$$$$
//ZZZ$ZZ7$$$$$$$Z$$Z$7ZZ78MMMMMMMMNDNNNND8NMMNNMMMNNDDD$,,,..7DDDDDDDD88DD888DDDDDNNDN,:,.,,:,,.....~DNZ$~,ZZZO$$Z$ZO$O$OO
//$$$$ZZZ$$$O$ZZZ$$$$7$ZZ$MMMMMMNMMMMMNNDNNNNDN$NDDNDDDN+::,$DDDDDDDDDDNDDDDDNNNNM8+.,,~.,,:,,,......ZD7$+:$$Z$Z$$Z$7Z$ZO$
//$$777$$$$ZZ$ZZ$ZZZ$$$O$7DNMMMMMMMMNNNNNMNN8DO.:8ODNNDDZ,~~88DDDDDDDDDNDDNNNNMN8:,:,:??~..::,,,,..,~8D7$=:$$$ZZ$$$7$ZZ$Z$
//$$$77777ZO$$$Z$ZZZZOZOO$DNNMMMMMNMNNNNMNNDDD8,:.:=7O8~~:~~?MNNNDDDDDNNNNNNNNNDZ~~:?~:.~$=.~::,:,,,:OO$$~:$77$7Z7$ZZZ7Z77
//Z$$$$ZZ$ZZ$ZOOZZZZZZOZZ$NMNND+==~IDDNNNMMDD8M:~~~:::~===++=$MNNNDDD8M?DNNDNNM$.~=~~:,,.,.7:::,,,,,,7$$$=:7$$$$7ZZ77$$ZZZ
//Z$ZZZZ$ZZ$ZZ$$OZZZZZO$O88MND~,~=,=IDNMMNNNDM,~~=======+???++8MMMNNNNN~~OMDDMI~=::~~,,,,...+::.,..,:,7$$+:I$Z$ZOZ$OZZ$$ZZ
//Z$7$$7$$7Z$ZZ$O$7ZZ$Z7$Z$$I:~:~=?I.7NNMNNMN$=~~=~+I77$$$777I?77$DDN$=~===+$I?+=??+=::,,::::Z~,....,:IZO+=7OOZ$OO8$ZOZOZZ
//OZ$Z7$$$$Z$7$$$Z$$$ZOZ$Z$ZZOI==~=7::$MMNNMDII?77$$$Z7$$O88DD$Z8O8Z++?????=~+II?I$$$I+=~==+?87:..,,,,~ZO?+7$ZZOOO$O8OZ$$Z
//7$ZZ$$7ZZZ7$ZZZZI$Z$ZZ8OZO$$ZI+~~?~,MMMNND=8MNM$$$7$$7$$7$$$$ZZO8888OZ$7+=?III77$$Z$$7I7IZ8O8,,...,,.IZ$I?$Z$ZZZ$7$$$ZOO
//$ZOO$$ZZ$7ZZ$Z7$$$$77Z$ZOOOZZ$?~II:.NNNNMI,.,:8II$$77Z$Z$$$$ZZ$ZZ$$Z$$$7Z$$7$$$$ZOZZZZO$+:ZO8I:.......$$$7ZZ7Z$$$$$77$$$
//$$ZZZZ$Z$$OZZZZZZ88$7$$ZZZZ$Z$$O$I::ONMM$::...,Z$7$$$$ZZ$$$$$$ZZ$ZOZZ$ZZZZ7$$ZZ88$OOO8$ZZ?.OOOI:.....,7Z8ZZ$$$$$ZOZZZ$$$
//OZZZO$$Z$ZZZZ$$$$Z$$$$7ZZZZOZ$$Z$=,,=MDN7=.....,7Z$ZZZZOZZO$ZZZ8D8OO8Z$Z$Z7ZZZ$OZO8O88$ZD+:.$ZZ:,..,.:O$$$ZZ7Z$$ZZOZZ$77
//ZZZZZ$Z8ZZZ$$$ZZZZ$7$$Z$ZZ$$$$$$$:,,..Z$7Z:,....ZOOZO88DDD8DNMMNNNNNDNMNDOZ$$Z$77OZO8OOZ8I:,.8O?:,,,:+7$$Z$8ZO$OO88OZOOO
//$ZZZZZ$ZZ$Z$$$$$ZZ$$Z$$7$$OO$O$O$~,..,=ND8$,...:INNNN8NNNNNNNNNNNNNNNNNNNMO$$I$O7ZZ8$ZO$Z$:,:+OO~::~,7$$ZZ$ZZZOZZZOZZOO8
//O8OO88DDODDDNNNNNNNDD88DDNDNNMMND+:,..$NDNN=...,$NNNM8MNNNNNNNNNNNNNNNNNNND8$ZZZZOOZOO$OZ$~,..OZ+,,,:Z$$$$7Z$ZZZZ$ZZZZZO
//NMNNNMNNMNNNDMNNMNNNNNNNNNMNNNNNDI:,.+MNNMNM+,.,ONNMMMDMMMMMNNNNNNNNNNNNNN8DDZZ$OZZZZZZ$$?:::,$O7:,:~$$Z$ZZZ$$$$$Z$$Z$$$
//88MDDNNNNDNDNNNNNNNNNNMNNMNNMDNNN?,,=DNNNMNDD,,.7NDNNNNMNNNNNNMNNNNNNNNNMNDON8ZZZZZZZZ$Z7=,,,+$$$~,,=7Z$ZZ$7$$$$$$$$$$$$
//Z8ZO$OZZONDNNNNNNNNNMMNMNDNMDDNDZ~,.$8DDDNDNO=..=MNDNMMDNNNNNNNNNNNNNNNNNDM88OO88OOZZ$$$I:,,,Z$$Z:.,+$$$Z$OZZ$ZZZ$$$Z$$$
//OO7ZZZZZ$$OZOOD8DO8DDND8D8NNDNNN?:..NOO$$O$O87...ONDNDNNNMMNNNNMMNDNNMNDMNM8NMN8ZOO88$OZ::,,I$$Z7:.,?$ZZ$$$Z$$Z$$$OO$$ZZ
//OZOZ$$$7Z$Z$$$ZZ$Z$Z$$ZOODDM$$MO:,~:OMNNN$Z77$...78ODZ888DNNNND8OZOO88OD8DD8DNDNMD8OOODI:.,=$Z$$I,..?$ZZ$ZZZZ$ZZZZOO88OO
//O$O$Z$7$Z$Z$$$$ZOO7ZZZ$$7ONZZ8ZI7++=$788D8ZZ$Z:::~ZZZZ7$I$$$$$$$$$$$$$77$$$Z$OONDNNNN8O~,,,Z$OZ$I~..IZ$ZO$$ZO8OOO88OO$ZO
//Z$OZ$$7ZZOZZZ$ZZOOOO8O$Z$ZZZZZ$Z$$O77Z$Z$$Z88Z?++?$Z$O7$$$$$$$O$$$$7$$$ZZ$ZZZ$$$Z$ZZ8Z==~~?Z$NDO?+~:$7$$Z$$O$$OZOZZ8DNNN
//O8ZZ$ZIZOOOZZ7$$OZZ$ZOZO$ZZ$OO$$Z8$$ZZ$$Z$$$Z7$7$Z$7ZZZZZDOOO8OOZZZ$$$$Z$ZOZZ$ZZ$$ZZZ$$$$$ZO$$Z$$77$Z$Z$$77ZZZZ$7ODMMMMM
//7Z78ZDIZZZZ7$Z7O$Z7ZZZ$ZZ$$$$O8$Z8ZOZ$ZZ$Z$ZO$$O$$OZZOO88OO88O8OZO8$8OZO$$$$$$OZ7IZ7I7Z7$O$O$$$O7$ZZZ$O$ZIZZZZODNNNNNNNN
//7$+?7III$ZZZOZZZ$$Z$$Z7$OZZZZZ$Z$ZOZZO$$7$Z$$8$OOO$7ZZO8OZOO8OOO$$O$OZO8$ZO$ZZO$7$$O$$ZZD8D8OZ8Z$$Z$888NDNNDNNNNNNNNNNNN
//I$77II?I7II+7Z$Z$Z$Z$ZO8IZZZZZZZ$7O7ZO$ZZOZOZZ$$$O8O7ZOOZ$ZOOOZZZOO$$8$$8ZZZ$O$7ZZZ88OZO8OODD8DD$8DNNNNNNNNNNNNNNNNNNNNN
//I?+?I??II?I7I+I$I$7OO$Z$ZZZZZZ$$ZZZOZZOZ8O88ZZOO$OZOO8OZZOOOZZ7OZOOO$7$ZZ$OZ$IZ$Z$7O$OO8OZZOD8OZMDNNNNNNNNNNNNNNNNNMMNNN
//I???7+7IIII7I77777$OOZZ7Z$$$Z$$Z$$$ZZZ$$OOOZZZZ$ZOOO88ZOZOZO7ZZZZOO87Z$7Z$$77$$ZZZZZD8$OOO$Z8O$8NMNN8NNNNNNNNNNNNNNNNNNN
//77?I$+?III7II?777$$O$OZZZZ$Z$OZ$$$$$OZZ$ZZZZZOZ$ZZ$ZOOZ$Z$7ZZZ$$$ZO$ZZZOZZZZ7$O$O7OZ$ZOOZOZZZ$$ZND8D8NNNNNNNNNNNMDMNNDDN
//7$77Z?$7I77$II7I?IIOZ$$$ZZ7Z$ZZZ$$7ZZZZ$ZZZ7OOZOZO$OOOO?IZ$7O$OO77OZZ$Z$Z$ZZZZZZ$$ZZOO$8ZOZ$OO$OZZ8ZDDNNNNNNNNNNDOO$NNZD
//N$$$I?I77I777I?I?7?+7$$$Z$$7ZZ$Z$$$$Z$$$$Z$$$Z$ZZZOZ$+I$$Z$$ZZ$ZO$$$ZZZZ$$77ZZ$$$O8ZZOOOZZZZ$ZOZZZ7$OOZDNNNNNNDO8OO$OZZO
//?7?$?$$$Z=IO77??II7777$I$$O$Z$O$$$$$77$7$Z$ZZ7$$$I77IZZZZ$$Z$$Z$$Z$$$7777$$Z77$ZZ$$$$$Z$$$ZZZ7Z$$Z$$OZ$O$O8DNDDZZ8Z8OZOZ
//DZZ$$=8ZZ77I?I+II77I$7$77$$7Z$$$$ZZ$$7$$7ZZZ77$O$ZI+7Z$$$ZZ$$7Z$Z$$$$Z$I$Z$$$$O$OZ$$$$$I7$Z$7Z$$ZZ$$Z$Z$O$$$$$ZZZZZ8ZOOO
